# don't even want the old compiler
set(LRCX_COMPILER_FLAGS "-std=c++11 -fvisibility=hidden")

include_compiler_flags()

if (LRCX_WARN_AS_ERROR)
	set(LRCX_COMPILER_FLAGS "-Wall -Werror ${LRCX_COMPILER_FLAGS}")
endif()

set(CMAKE_C_FLAGS_DEBUG "-D_DEBUG ${CMAKE_C_FLAGS_DEBUG}")
set(CMAKE_CXX_FLAGS_DEBUG "-D_DEBUG ${CMAKE_CXX_FLAGS_DEBUG}")

set(CMAKE_C_FLAGS "${LRCX_COMPILER_FLAGS} ${CMAKE_C_FLAGS}")
set(CMAKE_CXX_FLAGS "${LRCX_COMPILER_FLAGS} ${CMAKE_CXX_FLAGS}")

set(CMAKE_EXE_LINKER_FLAGS_RELEASE "-s ${CMAKE_EXE_LINKER_FLAGS_RELEASE}")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "-s ${CMAKE_SHARED_LINKER_FLAGS_RELEASE}")
